export const CLIENT_ID = "134SmCHaKfUPjMqzjT_Saw";

export const API_KEY =
  "gErXrCWz7SGZ6mjEMgqwyUhQsD1BUAgL73DjqMuPvtCSzMIarxsDQoyhFedjNVLKe4TZkJcgAkqhoM8BZTl9ci5wD7rEC3XzKdHAgWDhcWz4tUWe8ghdWbeYjjLwXXYx";
